#!/usr/bin/env python3
"""Run the current strict typing gate.

The gate starts with pure helper modules and expands as HA-facing modules get
fixture-backed tests and typed stubs.
"""

from __future__ import annotations

import subprocess
import sys

STRICT_TARGETS = (
    "custom_components/bticino_c300x/__init__.py",
    "custom_components/bticino_c300x/action.py",
    "custom_components/bticino_c300x/activation_address.py",
    "custom_components/bticino_c300x/agent_diagnostics.py",
    "custom_components/bticino_c300x/agent_contracts",
    "custom_components/bticino_c300x/agent_update.py",
    "custom_components/bticino_c300x/api.py",
    "custom_components/bticino_c300x/api_errors.py",
    "custom_components/bticino_c300x/api_validation.py",
    "custom_components/bticino_c300x/binary_sensor.py",
    "custom_components/bticino_c300x/blueprint_installer.py",
    "custom_components/bticino_c300x/button.py",
    "custom_components/bticino_c300x/capabilities.py",
    "custom_components/bticino_c300x/callback_url.py",
    "custom_components/bticino_c300x/callback_target.py",
    "custom_components/bticino_c300x/camera.py",
    "custom_components/bticino_c300x/camera_media/__init__.py",
    "custom_components/bticino_c300x/camera_media/home_call_ws.py",
    "custom_components/bticino_c300x/config_schemas.py",
    "custom_components/bticino_c300x/config_audio.py",
    "custom_components/bticino_c300x/config_flow.py",
    "custom_components/bticino_c300x/config_flow_activations.py",
    "custom_components/bticino_c300x/config_flow_dashboard.py",
    "custom_components/bticino_c300x/config_flow_features.py",
    "custom_components/bticino_c300x/config_flow_forms.py",
    "custom_components/bticino_c300x/config_flow_input.py",
    "custom_components/bticino_c300x/const.py",
    "custom_components/bticino_c300x/dashboard_weather.py",
    "custom_components/bticino_c300x/dashboard_entities.py",
    "custom_components/bticino_c300x/dashboard_labels.py",
    "custom_components/bticino_c300x/data.py",
    "custom_components/bticino_c300x/device_activations.py",
    "custom_components/bticino_c300x/device_installer.py",
    "custom_components/bticino_c300x/device_user.py",
    "custom_components/bticino_c300x/diagnostics.py",
    "custom_components/bticino_c300x/discovery.py",
    "custom_components/bticino_c300x/doorbell_state.py",
    "custom_components/bticino_c300x/doorstation_audio.py",
    "custom_components/bticino_c300x/entry_config.py",
    "custom_components/bticino_c300x/entry_locks.py",
    "custom_components/bticino_c300x/entry_types.py",
    "custom_components/bticino_c300x/entity.py",
    "custom_components/bticino_c300x/error_text.py",
    "custom_components/bticino_c300x/event.py",
    "custom_components/bticino_c300x/event_payload.py",
    "custom_components/bticino_c300x/event_types.py",
    "custom_components/bticino_c300x/events.py",
    "custom_components/bticino_c300x/exceptions.py",
    "custom_components/bticino_c300x/executor.py",
    "custom_components/bticino_c300x/fingerprint.py",
    "custom_components/bticino_c300x/frontend.py",
    "custom_components/bticino_c300x/json_io.py",
    "custom_components/bticino_c300x/camera_media/rtsp_orchestrator.py",
    "custom_components/bticino_c300x/camera_media/rtsp_policy.py",
    "custom_components/bticino_c300x/camera_media/rtsp_probe.py",
    "custom_components/bticino_c300x/camera_media/rtsp_url.py",
    "custom_components/bticino_c300x/camera_media/sdp.py",
    "custom_components/bticino_c300x/camera_media/state_machine.py",
    "custom_components/bticino_c300x/camera_media/webrtc_session.py",
    "custom_components/bticino_c300x/forwarding.py",
    "custom_components/bticino_c300x/media.py",
    "custom_components/bticino_c300x/media_setup.py",
    "custom_components/bticino_c300x/media_readiness.py",
    "custom_components/bticino_c300x/media_source.py",
    "custom_components/bticino_c300x/media_status.py",
    "custom_components/bticino_c300x/media_timeline.py",
    "custom_components/bticino_c300x/media_watchdog.py",
    "custom_components/bticino_c300x/memos.py",
    "custom_components/bticino_c300x/message_metadata.py",
    "custom_components/bticino_c300x/message_refresh.py",
    "custom_components/bticino_c300x/mqtt_migration.py",
    "custom_components/bticino_c300x/number.py",
    "custom_components/bticino_c300x/qml_patch.py",
    "custom_components/bticino_c300x/repair_flows_device_user.py",
    "custom_components/bticino_c300x/repair_flows_frontend.py",
    "custom_components/bticino_c300x/repair_issues.py",
    "custom_components/bticino_c300x/ring_ai.py",
    "custom_components/bticino_c300x/repairs.py",
    "custom_components/bticino_c300x/ring_capture.py",
    "custom_components/bticino_c300x/ring_decision.py",
    "custom_components/bticino_c300x/ring_talkback.py",
    "custom_components/bticino_c300x/select.py",
    "custom_components/bticino_c300x/sensor.py",
    "custom_components/bticino_c300x/service_schema.py",
    "custom_components/bticino_c300x/services.py",
    "custom_components/bticino_c300x/switch.py",
    "custom_components/bticino_c300x/use_cases/__init__.py",
    "custom_components/bticino_c300x/use_cases/common.py",
    "custom_components/bticino_c300x/use_cases/device_actions.py",
    "custom_components/bticino_c300x/use_cases/doorbell_video.py",
    "custom_components/bticino_c300x/use_cases/home_call.py",
    "custom_components/bticino_c300x/use_cases/maintenance.py",
    "custom_components/bticino_c300x/use_cases/memos.py",
    "custom_components/bticino_c300x/use_cases/messages.py",
    "custom_components/bticino_c300x/use_cases/ring_analysis.py",
    "custom_components/bticino_c300x/use_cases/ring_call.py",
    "custom_components/bticino_c300x/use_cases/ring_capture.py",
    "custom_components/bticino_c300x/stored_items.py",
    "custom_components/bticino_c300x/value_parsing.py",
    "custom_components/bticino_c300x/validation_patterns.py",
    "custom_components/bticino_c300x/video.py",
    "custom_components/bticino_c300x/video_messages.py",
    "custom_components/bticino_c300x/webhook.py",
    "scripts/build_hacs_release.py",
    "scripts/check_release_tag.py",
    "scripts/check_stack_usage.py",
    "scripts/check_quality_scale.py",
    "scripts/check_coverage.py",
    "scripts/check_frontend_lts.py",
    "scripts/check_ha_deprecations.py",
    "scripts/check_media_contracts.py",
    "scripts/check_repo.py",
    "scripts/check_typing.py",
    "scripts/check_validate.py",
    "scripts/device_routing_builder.py",
    "scripts/extract_pcap_fingerprint.py",
    "scripts/ha_https_proxy.py",
    "scripts/manifest_version.py",
    "scripts/smoke_ha.py",
    "scripts/stage_device_agent_bundle.py",
    "scripts/update_frontend_hashes.py",
    "scripts/verify_media_reference_flow.py",
    "scripts/write_release_assets.py",
)


def main() -> int:
    return subprocess.run(
        [
            sys.executable,
            "-m",
            "mypy",
            "--strict",
            "--ignore-missing-imports",
            "--follow-imports=silent",
            *STRICT_TARGETS,
        ],
        check=False,
    ).returncode


if __name__ == "__main__":
    sys.exit(main())
